services:
  postgres-jwt:
    image: postgres:14
    container_name: postgres-jwt
    environment:
      POSTGRES_DB: jwt_db
      POSTGRES_USER: jwt_user
      POSTGRES_PASSWORD: jwt_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data-jwt:/var/lib/postgresql/data

  pgadmin-jwt:
    image: dpage/pgadmin4:9.3
    container_name: pgadmin-jwt
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-jwt

volumes:
  postgres_data-jwt: